### ISSUE TITLE
Animating the transitions between wait-loading and wait-done?

### ISSUE THREAD

**Issue by sstorie** [michikono/angular-wait#2]
I'm going to play around with this a little, but do you have any quick guidance on how I could leverage angular animations to smoothly transition between the two states provided by this directive? 

I'm thinking just something as simple as fade out the loading content and immediately fade in the done content. I'm new to angular animations so thanks in advance for any help if you've considered this already.

**Comment by michikono** [comment]
I don't think this is an angular animation issue (although you could try to do it that way). Try adding CSS transition logic to the content inside. Think of this directive as an invisible wrapper. So for example:

``` html
<wait until...="myVar">
    <wait-done>
        <div class="fade-in-transition" ng-show="myVar"> ...
```

And add a CSS transition to animate the inner div in. 

``` css
.fade-in-transition {
    -webkit-transition:all linear 0.5s;
    transition:all linear 0.5s;
}
.fade-in-transition.ng-hide {
    opacity:0;
}
```

Let me know if this helps.
